environment:
  matrix:
    # node.js
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "4"
    - nodejs_version: "0.12"

install:
  - ps: Install-Product node $env:nodejs_version

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm install
  - cmd: npm test

# Don't actually build.
build: off
